### ISSUE TITLE
[Disk replacement] Honor disk size while replacing disks in cspc pool 

### ISSUE THREAD

**Issue by gprasath** [openebs/e2e-tests#187]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by nsathyaseelan** [comment]
Disk replacement test case been automated and it's available in this repo https://github.com/openebs/cstor-operators/tree/master/e2e-tests/experiments/functional/cspc-pool/disk-replacement
