### ISSUE TITLE
Document the E2e setup details.

### ISSUE THREAD

**Issue by kmova** [openebs/e2e-tests#193]
Document the way OpenEBS E2e setup is built and run. 

https://github.com/openebs/e2e-tests/wiki/On-premise-E2e-Setup-using-GitLab

**Comment by shashank855** [comment]
Oenshift 4.2 setup details: https://docs.google.com/document/d/1C4TXdd-ZSror66F_AdQNBP9q3fxN9_vaoYUDuoIMIoQ/edit

**Comment by shashank855** [comment]
Gitlab setup and troubleshooting DOC: https://docs.google.com/document/d/150m696Kc6n85dppeFKMK6fwCTac3M84sCyP64k6mJeA/edit#heading=h.az0qx7ucyh1k
