### ISSUE TITLE
E2e Log collection using ECK 

### ISSUE THREAD

**Issue by kmova** [openebs/e2e-tests#194]
Documentation on how to setup and maintain. 
Documentation on how to login and check for logs by developers.

**Comment by shashank855** [comment]
ECk setup docs: https://docs.google.com/document/d/1uGfBT6PWpVdNMC65CZBgQB63JPv_KeX9RlJ2J1Tugh4/edit

**Comment by shashank855** [comment]
- The above doc link contains setup details and cluster credentials has been shared in team credential sheet.
- Dev team can view test related logs at http://eck.openebs100.io:5603, based on supported filters like pipelineID and commit ID.
