### ISSUE TITLE
Upgrade OpenEBS CI GitLab to Kubernetes 1.17

### ISSUE THREAD

**Issue by kmova** [openebs/e2e-tests#228]
=> GitLab is running on 3.10, with Kubernetes 1.10
=> Stateful workloads on OpenEBS 1.8
=> No upgrade from 3.10 openshift to 4.2

=> OpenShift 4.2 - has certificate expiry issues. 
=> Migrate GitLab from 3.10 openshift to native Kubernetes 1.17. 
=> Steps:
      * setup new 1.17 K8s cluster (5 nodes)
      * OpenEBS 1.8 
      * Setup minio on Local PV for migration 
      * Backup (GitLab with data) from 3.10 volumes to MinIO
      * Restore from MinIO into new cluster
      * Verify new setup is operational
      * Archive/delete old setup.

**Comment by shashank855** [comment]
Gitlab migrated to kubernetes 1.18.3
