### ISSUE TITLE
Disable the gathering facts task in the test cases

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/e2e-tests#438]
- While running the test cases sometimes gathering facts task gives time out error as it doesn't gathers all the facts in default gathering time

```
TASK [Gathering Facts] *********************************************************
2020-07-08T22:19:40.138535 (delta: 0.077119)         elapsed: 0.380455 ******** 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TimeoutError: Timer expired after 10 seconds
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/bin/lsblk --list --noheadings --paths --output NAME,UUID --exclude 2", "msg": "Timer expired after 10 seconds", "rc": 257}
	to retry, use: --limit @/apps/busybox/deployers/test.retry
```
- To avoid this disable the facts. Disabling facts as mostly no system info is being used in ansible-playbooks, As the test cases using local host no need to have all the facts
  `gather_facts: False`

**Comment by shashank855** [comment]
PR ref:  https://github.com/openebs/e2e-tests/pull/441

**Comment by shashank855** [comment]
@nsathyaseelan Can we close this as the above PR has already merged.
